"""
편입 VOCA 주요 단어들의 반의어(antonym) 데이터를 vocab.json에 추가하는 스크립트.

편입 시험에서 자주 출제되는 다의어/비유어 단어들을 중심으로,
정답과 의미적으로 대립되는 반의어를 오답 선지로 활용하기 위한 데이터를 구축한다.
"""
import json

# 편입 시험에서 자주 출제되는 단어들의 반의어 데이터
# 형식: { "단어": ["반의어1", "반의어2", ...] }
ANTONYM_DATA = {
    # 성격·태도
    "bloated": ["humble", "modest", "meek", "unpretentious"],
    "haughty": ["humble", "modest", "meek", "deferential"],
    "arrogant": ["humble", "modest", "meek", "unassuming"],
    "supercilious": ["humble", "respectful", "deferential"],
    "imperious": ["humble", "submissive", "deferential"],
    "obsequious": ["assertive", "independent", "defiant"],
    "sycophantic": ["sincere", "independent", "candid"],
    "servile": ["assertive", "independent", "dominant"],
    "insolent": ["respectful", "polite", "deferential"],
    "impertinent": ["respectful", "polite", "courteous"],
    "impudent": ["respectful", "polite", "modest"],
    "audacious": ["timid", "cautious", "cowardly"],
    "brazen": ["modest", "timid", "bashful"],
    "presumptuous": ["modest", "humble", "deferential"],
    "pompous": ["humble", "modest", "unpretentious"],
    "ostentatious": ["modest", "understated", "unassuming"],
    "flamboyant": ["modest", "understated", "subdued"],
    "vainglorious": ["humble", "modest", "self-effacing"],

    # 긍정·부정 성격
    "benevolent": ["malevolent", "cruel", "callous"],
    "malevolent": ["benevolent", "kind", "compassionate"],
    "magnanimous": ["petty", "mean-spirited", "ungenerous"],
    "munificent": ["stingy", "miserly", "parsimonious"],
    "parsimonious": ["generous", "munificent", "lavish"],
    "miserly": ["generous", "lavish", "munificent"],
    "frugal": ["extravagant", "wasteful", "lavish"],
    "profligate": ["frugal", "thrifty", "economical"],
    "prodigal": ["frugal", "thrifty", "economical"],
    "lavish": ["frugal", "thrifty", "parsimonious"],
    "niggardly": ["generous", "lavish", "munificent"],
    "penurious": ["generous", "wealthy", "affluent"],

    # 감정·심리
    "sanguine": ["pessimistic", "despondent", "gloomy"],
    "optimistic": ["pessimistic", "despondent", "cynical"],
    "pessimistic": ["optimistic", "sanguine", "hopeful"],
    "despondent": ["hopeful", "cheerful", "sanguine"],
    "melancholy": ["cheerful", "joyful", "elated"],
    "elated": ["despondent", "dejected", "melancholy"],
    "euphoric": ["despondent", "melancholy", "dejected"],
    "dejected": ["elated", "cheerful", "buoyant"],
    "morose": ["cheerful", "jovial", "buoyant"],
    "sullen": ["cheerful", "affable", "genial"],
    "jovial": ["morose", "sullen", "gloomy"],
    "ebullient": ["subdued", "morose", "dejected"],
    "exuberant": ["subdued", "restrained", "morose"],
    "vivacious": ["subdued", "lethargic", "listless"],
    "lethargic": ["energetic", "vivacious", "animated"],
    "listless": ["energetic", "animated", "enthusiastic"],
    "languid": ["energetic", "vigorous", "animated"],

    # 지적 능력
    "astute": ["naive", "obtuse", "gullible"],
    "perspicacious": ["obtuse", "naive", "imperceptive"],
    "sagacious": ["foolish", "obtuse", "naive"],
    "obtuse": ["astute", "perceptive", "perspicacious"],
    "naive": ["astute", "shrewd", "sophisticated"],
    "gullible": ["skeptical", "astute", "discerning"],
    "credulous": ["skeptical", "incredulous", "discerning"],
    "skeptical": ["credulous", "gullible", "naive"],
    "discerning": ["obtuse", "undiscriminating", "naive"],
    "erudite": ["ignorant", "unlearned", "illiterate"],
    "pedantic": ["informal", "casual", "unpretentious"],
    "esoteric": ["common", "accessible", "popular"],
    "abstruse": ["clear", "accessible", "lucid"],
    "recondite": ["common", "accessible", "familiar"],

    # 말·표현
    "loquacious": ["taciturn", "reticent", "laconic"],
    "garrulous": ["taciturn", "reticent", "laconic"],
    "verbose": ["concise", "laconic", "terse"],
    "taciturn": ["loquacious", "garrulous", "talkative"],
    "reticent": ["forthcoming", "communicative", "loquacious"],
    "laconic": ["verbose", "loquacious", "garrulous"],
    "terse": ["verbose", "loquacious", "wordy"],
    "succinct": ["verbose", "wordy", "long-winded"],
    "eloquent": ["inarticulate", "tongue-tied", "incoherent"],
    "articulate": ["inarticulate", "tongue-tied", "incoherent"],
    "inarticulate": ["eloquent", "articulate", "fluent"],
    "candid": ["evasive", "deceptive", "dishonest"],
    "forthright": ["evasive", "deceptive", "reticent"],
    "evasive": ["candid", "forthright", "direct"],
    "equivocal": ["unambiguous", "clear", "definitive"],
    "ambiguous": ["clear", "unambiguous", "definitive"],
    "unequivocal": ["ambiguous", "equivocal", "vague"],

    # 도덕·윤리
    "virtuous": ["corrupt", "depraved", "vicious"],
    "corrupt": ["virtuous", "honest", "upright"],
    "depraved": ["virtuous", "moral", "upright"],
    "scrupulous": ["unscrupulous", "dishonest", "corrupt"],
    "unscrupulous": ["scrupulous", "honest", "ethical"],
    "duplicitous": ["sincere", "honest", "candid"],
    "mendacious": ["truthful", "honest", "candid"],
    "veracious": ["mendacious", "dishonest", "deceptive"],
    "perfidious": ["loyal", "faithful", "trustworthy"],
    "treacherous": ["loyal", "faithful", "trustworthy"],
    "loyal": ["treacherous", "perfidious", "disloyal"],
    "steadfast": ["fickle", "wavering", "irresolute"],
    "fickle": ["steadfast", "loyal", "constant"],
    "capricious": ["steadfast", "consistent", "predictable"],
    "erratic": ["consistent", "predictable", "steady"],

    # 크기·정도
    "copious": ["scarce", "meager", "sparse"],
    "abundant": ["scarce", "meager", "deficient"],
    "scarce": ["abundant", "copious", "plentiful"],
    "meager": ["abundant", "copious", "plentiful"],
    "sparse": ["dense", "abundant", "copious"],
    "prolific": ["barren", "unproductive", "infertile"],
    "barren": ["fertile", "prolific", "productive"],
    "fertile": ["barren", "infertile", "sterile"],
    "diminutive": ["enormous", "gigantic", "colossal"],
    "colossal": ["diminutive", "tiny", "minuscule"],
    "minuscule": ["colossal", "enormous", "gigantic"],
    "immense": ["tiny", "minuscule", "diminutive"],

    # 속도·시간
    "expeditious": ["slow", "dilatory", "sluggish"],
    "dilatory": ["expeditious", "prompt", "swift"],
    "sluggish": ["energetic", "swift", "expeditious"],
    "prompt": ["dilatory", "tardy", "sluggish"],
    "tardy": ["prompt", "punctual", "expeditious"],
    "transient": ["permanent", "enduring", "lasting"],
    "ephemeral": ["permanent", "enduring", "lasting"],
    "permanent": ["transient", "ephemeral", "fleeting"],
    "enduring": ["transient", "ephemeral", "fleeting"],
    "fleeting": ["enduring", "permanent", "lasting"],
    "perpetual": ["temporary", "transient", "fleeting"],
    "temporary": ["permanent", "enduring", "perpetual"],

    # 강함·약함
    "robust": ["frail", "feeble", "fragile"],
    "vigorous": ["feeble", "lethargic", "languid"],
    "stalwart": ["frail", "feeble", "weak"],
    "tenacious": ["irresolute", "wavering", "feeble"],
    "resolute": ["irresolute", "wavering", "vacillating"],
    "irresolute": ["resolute", "determined", "steadfast"],
    "vacillating": ["resolute", "steadfast", "determined"],
    "frail": ["robust", "sturdy", "vigorous"],
    "feeble": ["robust", "vigorous", "stalwart"],
    "fragile": ["robust", "sturdy", "durable"],
    "durable": ["fragile", "frail", "ephemeral"],

    # 순종·반항
    "docile": ["defiant", "rebellious", "obstinate"],
    "compliant": ["defiant", "rebellious", "recalcitrant"],
    "submissive": ["defiant", "assertive", "dominant"],
    "defiant": ["docile", "compliant", "submissive"],
    "rebellious": ["docile", "compliant", "obedient"],
    "recalcitrant": ["docile", "compliant", "cooperative"],
    "obstinate": ["flexible", "compliant", "amenable"],
    "intractable": ["docile", "compliant", "tractable"],
    "tractable": ["intractable", "obstinate", "recalcitrant"],
    "amenable": ["obstinate", "intractable", "recalcitrant"],
    "obdurate": ["flexible", "amenable", "compliant"],
    "pertinacious": ["flexible", "yielding", "compliant"],

    # 명확·모호
    "lucid": ["obscure", "opaque", "abstruse"],
    "pellucid": ["obscure", "opaque", "murky"],
    "transparent": ["opaque", "obscure", "murky"],
    "opaque": ["transparent", "lucid", "pellucid"],
    "obscure": ["clear", "lucid", "transparent"],
    "perspicuous": ["obscure", "opaque", "abstruse"],
    "cryptic": ["clear", "lucid", "transparent"],
    "enigmatic": ["clear", "transparent", "lucid"],
    "inscrutable": ["transparent", "clear", "readable"],

    # 감사·비난
    "laudatory": ["critical", "derogatory", "disparaging"],
    "eulogistic": ["critical", "derogatory", "disparaging"],
    "derogatory": ["laudatory", "complimentary", "flattering"],
    "disparaging": ["laudatory", "complimentary", "flattering"],
    "censure": ["praise", "commend", "laud"],
    "reproach": ["praise", "commend", "laud"],
    "rebuke": ["praise", "commend", "approve"],
    "castigate": ["praise", "commend", "laud"],
    "excoriate": ["praise", "commend", "laud"],
    "laud": ["censure", "reproach", "castigate"],
    "commend": ["censure", "reproach", "rebuke"],
    "extol": ["censure", "disparage", "belittle"],

    # 증가·감소
    "augment": ["diminish", "reduce", "curtail"],
    "amplify": ["diminish", "reduce", "attenuate"],
    "exacerbate": ["alleviate", "mitigate", "ameliorate"],
    "aggravate": ["alleviate", "mitigate", "ameliorate"],
    "alleviate": ["aggravate", "exacerbate", "worsen"],
    "mitigate": ["aggravate", "exacerbate", "intensify"],
    "ameliorate": ["worsen", "aggravate", "exacerbate"],
    "diminish": ["augment", "amplify", "increase"],
    "curtail": ["expand", "extend", "augment"],
    "attenuate": ["amplify", "augment", "strengthen"],
    "bolster": ["undermine", "weaken", "diminish"],
    "undermine": ["bolster", "strengthen", "support"],

    # 지지·반대
    "advocate": ["oppose", "denounce", "condemn"],
    "endorse": ["oppose", "denounce", "condemn"],
    "espouse": ["oppose", "reject", "denounce"],
    "denounce": ["advocate", "endorse", "support"],
    "condemn": ["praise", "endorse", "advocate"],
    "sanction": ["prohibit", "condemn", "denounce"],
    "prohibit": ["permit", "sanction", "allow"],
    "proscribe": ["permit", "sanction", "allow"],
    "forbid": ["permit", "allow", "sanction"],
    "permit": ["prohibit", "forbid", "proscribe"],

    # 확실·불확실
    "certain": ["uncertain", "dubious", "equivocal"],
    "dubious": ["certain", "definite", "unequivocal"],
    "tentative": ["definite", "certain", "resolute"],
    "definitive": ["tentative", "uncertain", "ambiguous"],
    "conclusive": ["inconclusive", "tentative", "uncertain"],
    "inconclusive": ["conclusive", "definitive", "certain"],

    # 기타 주요 편입 단어
    "benign": ["malignant", "harmful", "pernicious"],
    "malignant": ["benign", "harmless", "beneficial"],
    "pernicious": ["benign", "harmless", "beneficial"],
    "innocuous": ["harmful", "pernicious", "malignant"],
    "salutary": ["harmful", "detrimental", "pernicious"],
    "detrimental": ["beneficial", "salutary", "advantageous"],
    "beneficial": ["detrimental", "harmful", "pernicious"],
    "noxious": ["harmless", "innocuous", "benign"],
    "toxic": ["harmless", "innocuous", "benign"],
    "salubrious": ["unhealthy", "noxious", "detrimental"],

    "novel": ["conventional", "traditional", "orthodox"],
    "innovative": ["conventional", "traditional", "orthodox"],
    "orthodox": ["novel", "innovative", "heterodox"],
    "heterodox": ["orthodox", "conventional", "traditional"],
    "conventional": ["novel", "innovative", "unconventional"],
    "radical": ["conservative", "moderate", "orthodox"],
    "conservative": ["radical", "progressive", "liberal"],
    "progressive": ["conservative", "reactionary", "orthodox"],

    "verbose": ["concise", "laconic", "terse"],
    "concise": ["verbose", "wordy", "long-winded"],
    "prolix": ["concise", "succinct", "laconic"],
    "succinct": ["verbose", "prolix", "long-winded"],

    "affluent": ["impoverished", "destitute", "indigent"],
    "opulent": ["impoverished", "destitute", "austere"],
    "impoverished": ["affluent", "opulent", "wealthy"],
    "destitute": ["affluent", "opulent", "prosperous"],
    "indigent": ["affluent", "opulent", "prosperous"],
    "austere": ["lavish", "opulent", "extravagant"],

    "placid": ["turbulent", "agitated", "tempestuous"],
    "serene": ["turbulent", "agitated", "tumultuous"],
    "tranquil": ["turbulent", "agitated", "tempestuous"],
    "turbulent": ["placid", "serene", "tranquil"],
    "tempestuous": ["placid", "serene", "calm"],
    "tumultuous": ["placid", "serene", "tranquil"],

    "mundane": ["extraordinary", "remarkable", "exceptional"],
    "banal": ["original", "novel", "remarkable"],
    "trite": ["original", "novel", "fresh"],
    "hackneyed": ["original", "novel", "fresh"],
    "cliche": ["original", "novel", "fresh"],
    "prosaic": ["poetic", "imaginative", "extraordinary"],
    "pedestrian": ["extraordinary", "remarkable", "exceptional"],

    "acrimonious": ["amicable", "cordial", "harmonious"],
    "contentious": ["amicable", "peaceful", "harmonious"],
    "belligerent": ["peaceful", "amicable", "conciliatory"],
    "pugnacious": ["peaceful", "amicable", "conciliatory"],
    "bellicose": ["peaceful", "amicable", "conciliatory"],
    "amicable": ["hostile", "acrimonious", "belligerent"],
    "conciliatory": ["belligerent", "hostile", "contentious"],
    "antagonistic": ["amicable", "friendly", "conciliatory"],
    "hostile": ["amicable", "friendly", "cordial"],

    "diligent": ["lazy", "indolent", "slothful"],
    "industrious": ["lazy", "indolent", "slothful"],
    "assiduous": ["lazy", "indolent", "negligent"],
    "sedulous": ["lazy", "indolent", "negligent"],
    "indolent": ["diligent", "industrious", "assiduous"],
    "slothful": ["diligent", "industrious", "energetic"],
    "negligent": ["diligent", "careful", "assiduous"],
    "remiss": ["diligent", "careful", "conscientious"],
    "conscientious": ["negligent", "remiss", "careless"],

    "prudent": ["reckless", "imprudent", "rash"],
    "circumspect": ["reckless", "imprudent", "careless"],
    "judicious": ["reckless", "imprudent", "foolish"],
    "reckless": ["prudent", "cautious", "circumspect"],
    "imprudent": ["prudent", "judicious", "circumspect"],
    "rash": ["prudent", "cautious", "deliberate"],

    "tacit": ["explicit", "stated", "expressed"],
    "implicit": ["explicit", "stated", "expressed"],
    "explicit": ["tacit", "implicit", "unstated"],
    "overt": ["covert", "hidden", "clandestine"],
    "covert": ["overt", "open", "explicit"],
    "clandestine": ["overt", "open", "public"],
    "surreptitious": ["overt", "open", "public"],
    "furtive": ["overt", "open", "forthright"],
    "stealthy": ["overt", "open", "forthright"],

    "gregarious": ["solitary", "reclusive", "antisocial"],
    "sociable": ["solitary", "reclusive", "antisocial"],
    "affable": ["unfriendly", "hostile", "antisocial"],
    "genial": ["unfriendly", "hostile", "sullen"],
    "reclusive": ["gregarious", "sociable", "outgoing"],
    "solitary": ["gregarious", "sociable", "outgoing"],
    "antisocial": ["gregarious", "sociable", "affable"],

    "pious": ["impious", "irreverent", "sacrilegious"],
    "devout": ["impious", "irreverent", "sacrilegious"],
    "reverent": ["irreverent", "disrespectful", "sacrilegious"],
    "impious": ["pious", "devout", "reverent"],
    "irreverent": ["reverent", "respectful", "pious"],
    "sacrilegious": ["reverent", "pious", "devout"],
    "blasphemous": ["reverent", "pious", "devout"],

    "sober": ["intoxicated", "frivolous", "flippant"],
    "grave": ["frivolous", "flippant", "lighthearted"],
    "solemn": ["frivolous", "flippant", "lighthearted"],
    "somber": ["cheerful", "lighthearted", "jovial"],
    "frivolous": ["serious", "grave", "solemn"],
    "flippant": ["serious", "grave", "solemn"],
    "levity": ["gravity", "solemnity", "seriousness"],
    "gravity": ["levity", "frivolity", "flippancy"],

    "amiable": ["hostile", "unfriendly", "antagonistic"],
    "cordial": ["hostile", "unfriendly", "cold"],
    "congenial": ["hostile", "unfriendly", "disagreeable"],
    "inimical": ["friendly", "amicable", "cordial"],

    "pragmatic": ["idealistic", "impractical", "utopian"],
    "idealistic": ["pragmatic", "realistic", "practical"],
    "utopian": ["pragmatic", "realistic", "practical"],
    "realistic": ["idealistic", "utopian", "impractical"],

    "abstract": ["concrete", "tangible", "specific"],
    "concrete": ["abstract", "vague", "intangible"],
    "tangible": ["abstract", "intangible", "vague"],
    "intangible": ["concrete", "tangible", "specific"],

    "objective": ["subjective", "biased", "partial"],
    "subjective": ["objective", "impartial", "unbiased"],
    "impartial": ["biased", "partial", "subjective"],
    "biased": ["impartial", "objective", "unbiased"],
    "partial": ["impartial", "objective", "unbiased"],

    "rational": ["irrational", "illogical", "absurd"],
    "irrational": ["rational", "logical", "sensible"],
    "logical": ["illogical", "irrational", "absurd"],
    "illogical": ["logical", "rational", "sensible"],

    "superficial": ["profound", "deep", "thorough"],
    "profound": ["superficial", "shallow", "trivial"],
    "shallow": ["profound", "deep", "thorough"],
    "thorough": ["superficial", "shallow", "cursory"],
    "cursory": ["thorough", "careful", "meticulous"],
    "meticulous": ["careless", "cursory", "negligent"],

    "lenient": ["strict", "harsh", "severe"],
    "indulgent": ["strict", "harsh", "austere"],
    "permissive": ["strict", "restrictive", "authoritarian"],
    "strict": ["lenient", "indulgent", "permissive"],
    "harsh": ["lenient", "gentle", "mild"],
    "severe": ["lenient", "mild", "gentle"],
    "austere": ["indulgent", "lavish", "lenient"],

    "ingenuous": ["disingenuous", "cunning", "devious"],
    "disingenuous": ["sincere", "candid", "ingenuous"],
    "guileless": ["cunning", "devious", "scheming"],
    "artless": ["cunning", "devious", "scheming"],
    "cunning": ["naive", "guileless", "artless"],
    "devious": ["straightforward", "candid", "honest"],
    "scheming": ["straightforward", "candid", "honest"],

    "vindictive": ["forgiving", "merciful", "magnanimous"],
    "vengeful": ["forgiving", "merciful", "magnanimous"],
    "forgiving": ["vindictive", "vengeful", "unforgiving"],
    "merciful": ["merciless", "cruel", "vindictive"],
    "merciless": ["merciful", "compassionate", "forgiving"],
    "ruthless": ["merciful", "compassionate", "humane"],
    "callous": ["compassionate", "empathetic", "sensitive"],
    "compassionate": ["callous", "ruthless", "merciless"],
    "empathetic": ["callous", "indifferent", "unsympathetic"],
    "indifferent": ["compassionate", "empathetic", "concerned"],

    "verbose": ["concise", "laconic", "terse"],
    "turgid": ["simple", "plain", "clear"],
    "bombastic": ["simple", "plain", "understated"],
    "grandiloquent": ["simple", "plain", "understated"],
    "florid": ["plain", "simple", "understated"],

    "placate": ["aggravate", "provoke", "antagonize"],
    "appease": ["aggravate", "provoke", "antagonize"],
    "mollify": ["aggravate", "provoke", "antagonize"],
    "pacify": ["aggravate", "provoke", "antagonize"],
    "provoke": ["placate", "appease", "mollify"],
    "antagonize": ["placate", "appease", "conciliate"],
    "aggravate": ["alleviate", "placate", "mollify"],

    "abrogate": ["enact", "establish", "ratify"],
    "nullify": ["validate", "ratify", "confirm"],
    "rescind": ["enact", "establish", "ratify"],
    "annul": ["validate", "ratify", "confirm"],
    "invalidate": ["validate", "ratify", "confirm"],
    "ratify": ["nullify", "rescind", "annul"],
    "validate": ["nullify", "invalidate", "annul"],
    "enact": ["repeal", "rescind", "abrogate"],
    "repeal": ["enact", "establish", "ratify"],

    "impede": ["facilitate", "expedite", "assist"],
    "hinder": ["facilitate", "expedite", "assist"],
    "obstruct": ["facilitate", "expedite", "assist"],
    "hamper": ["facilitate", "expedite", "assist"],
    "facilitate": ["impede", "hinder", "obstruct"],
    "expedite": ["impede", "hinder", "delay"],
    "accelerate": ["decelerate", "impede", "hinder"],
    "decelerate": ["accelerate", "expedite", "facilitate"],

    "exacerbate": ["alleviate", "mitigate", "ameliorate"],
    "ameliorate": ["exacerbate", "worsen", "aggravate"],
    "deteriorate": ["improve", "ameliorate", "recover"],
    "improve": ["deteriorate", "worsen", "decline"],
    "worsen": ["improve", "ameliorate", "recover"],

    "nascent": ["mature", "developed", "established"],
    "incipient": ["mature", "developed", "established"],
    "mature": ["nascent", "incipient", "immature"],
    "obsolete": ["current", "modern", "contemporary"],
    "archaic": ["modern", "contemporary", "current"],
    "antiquated": ["modern", "contemporary", "current"],
    "contemporary": ["obsolete", "archaic", "antiquated"],
    "modern": ["obsolete", "archaic", "antiquated"],

    "exorbitant": ["reasonable", "moderate", "fair"],
    "extravagant": ["frugal", "economical", "moderate"],
    "excessive": ["moderate", "reasonable", "restrained"],
    "moderate": ["excessive", "exorbitant", "extreme"],
    "restrained": ["excessive", "extravagant", "unrestrained"],
    "temperate": ["excessive", "immoderate", "extreme"],
    "immoderate": ["temperate", "moderate", "restrained"],

    "benevolent": ["malevolent", "cruel", "callous"],
    "philanthropic": ["misanthropic", "selfish", "callous"],
    "altruistic": ["selfish", "egoistic", "self-centered"],
    "selfish": ["altruistic", "generous", "philanthropic"],
    "egoistic": ["altruistic", "selfless", "generous"],

    "credible": ["incredible", "implausible", "dubious"],
    "plausible": ["implausible", "incredible", "dubious"],
    "implausible": ["plausible", "credible", "believable"],
    "incredible": ["credible", "plausible", "believable"],
    "dubious": ["credible", "certain", "definite"],

    "prolific": ["barren", "unproductive", "sterile"],
    "fecund": ["barren", "sterile", "infertile"],
    "fertile": ["barren", "sterile", "infertile"],
    "barren": ["fertile", "prolific", "fecund"],
    "sterile": ["fertile", "fecund", "prolific"],
    "infertile": ["fertile", "fecund", "prolific"],

    "arid": ["fertile", "lush", "verdant"],
    "verdant": ["arid", "barren", "desolate"],
    "lush": ["arid", "barren", "sparse"],
    "desolate": ["fertile", "lush", "verdant"],

    "opaque": ["transparent", "lucid", "clear"],
    "translucent": ["opaque", "transparent"],
    "pellucid": ["opaque", "murky", "turbid"],
    "murky": ["clear", "transparent", "pellucid"],
    "turbid": ["clear", "pellucid", "transparent"],

    "volatile": ["stable", "steady", "constant"],
    "stable": ["volatile", "unstable", "erratic"],
    "erratic": ["stable", "consistent", "steady"],
    "consistent": ["erratic", "volatile", "inconsistent"],
    "steadfast": ["fickle", "wavering", "erratic"],

    "benign": ["malignant", "harmful", "pernicious"],
    "malignant": ["benign", "harmless", "beneficial"],
    "pernicious": ["benign", "harmless", "salutary"],
    "salutary": ["pernicious", "harmful", "detrimental"],
    "innocuous": ["harmful", "pernicious", "toxic"],

    "frugal": ["extravagant", "wasteful", "profligate"],
    "thrifty": ["extravagant", "wasteful", "profligate"],
    "economical": ["wasteful", "extravagant", "profligate"],
    "wasteful": ["frugal", "thrifty", "economical"],
    "extravagant": ["frugal", "thrifty", "economical"],

    "incessant": ["intermittent", "sporadic", "occasional"],
    "perpetual": ["temporary", "intermittent", "sporadic"],
    "intermittent": ["incessant", "perpetual", "continuous"],
    "sporadic": ["incessant", "perpetual", "continuous"],
    "continuous": ["intermittent", "sporadic", "occasional"],
    "occasional": ["incessant", "perpetual", "continuous"],

    "mundane": ["extraordinary", "exceptional", "remarkable"],
    "extraordinary": ["mundane", "ordinary", "commonplace"],
    "commonplace": ["extraordinary", "exceptional", "remarkable"],
    "exceptional": ["mundane", "ordinary", "commonplace"],
    "remarkable": ["mundane", "ordinary", "unremarkable"],
    "unremarkable": ["extraordinary", "exceptional", "remarkable"],

    "verbose": ["concise", "laconic", "terse"],
    "wordy": ["concise", "succinct", "laconic"],
    "long-winded": ["concise", "succinct", "terse"],
    "concise": ["verbose", "wordy", "long-winded"],
    "succinct": ["verbose", "wordy", "long-winded"],
    "laconic": ["verbose", "wordy", "garrulous"],
    "terse": ["verbose", "wordy", "garrulous"],
}

def add_antonyms():
    with open('/home/ubuntu/vocaknio-quiz/assets/vocab.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    added = 0
    for item in data:
        word = item.get('w', '').lower()
        if word in ANTONYM_DATA:
            item['antonym'] = ANTONYM_DATA[word]
            added += 1
    
    with open('/home/ubuntu/vocaknio-quiz/assets/vocab.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, separators=(',', ':'))
    
    print(f"반의어 추가 완료: {added}개 단어에 antonym 필드 추가")
    
    # 검증
    with open('/home/ubuntu/vocaknio-quiz/assets/vocab.json', 'r', encoding='utf-8') as f:
        data2 = json.load(f)
    for item in data2:
        if item.get('w','').lower() == 'bloated':
            print("bloated 확인:", json.dumps(item, ensure_ascii=False, indent=2))
            break

if __name__ == '__main__':
    add_antonyms()
